export const settingsData = {
  revLevel: '0_0_3',
  memberSince: '01/01/2023',
  userName: 'fpanthony3',
  password: '********',
  firstName: 'Fred',
  lastName: 'Anthony III',
  email: 'fpanthony3@gmail.com',
  mobile: '+1 610 570 8569',
  country: 'United States',
  state: 'PA',
  address: '5464 2nd Street',
  city: 'Whitehall',
  zip: '18052',
  language: 'English',
  theme: 'blue',
  subscriptionLevel: 0,
  subscription: 'Genie',
  defaultExchange: 'kucoin',
};
