export const stockSignals = {
  signals: [
    {
      ticker: 'TSLA',
      shtSignal: 'SELL',
      mdmSignal: 'WAIT',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'AMZN',
      shtSignal: 'SELL',
      mdmSignal: 'BUY',
      lngSignal: 'BUY',
      favorite: true,
    },
    {
      ticker: 'SOFI',
      shtSignal: 'DUMP',
      mdmSignal: 'BUY',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'AMD',
      shtSignal: 'HOLD',
      mdmSignal: 'SELL',
      lngSignal: 'SELL',
      favorite: false,
    },
    {
      ticker: 'NVDA',
      shtSignal: 'DUMP',
      mdmSignal: 'BUY',
      lngSignal: 'BUY',
      favorite: false,
    },
    {
      ticker: 'LCID',
      shtSignal: 'HOLD',
      mdmSignal: 'SELL',
      lngSignal: 'SELL',
      favorite: false,
    },
    {
      ticker: 'INTC',
      shtSignal: 'SELL',
      mdmSignal: 'BUY',
      lngSignal: 'BUY',
      favorite: false,
    },
    {
      ticker: 'AAPL',
      shtSignal: 'SELL',
      mdmSignal: 'DUMP',
      lngSignal: 'BUY',
      favorite: false,
    },
    {
      ticker: 'BZFD',
      shtSignal: 'DUMP',
      mdmSignal: 'SELL',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'RIVN',
      shtSignal: 'HOLD',
      mdmSignal: 'WAIT',
      lngSignal: 'DUMP',
      favorite: false,
    },
    {
      ticker: 'AGNC',
      shtSignal: 'DUMP',
      mdmSignal: 'HOLD',
      lngSignal: 'SELL',
      favorite: false,
    },
    {
      ticker: 'BBBY',
      shtSignal: 'WAIT',
      mdmSignal: 'SELL',
      lngSignal: 'DUMP',
      favorite: false,
    },
    {
      ticker: 'MU',
      shtSignal: 'BUY',
      mdmSignal: 'SELL',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'META',
      shtSignal: 'WAIT',
      mdmSignal: 'WAIT',
      lngSignal: 'DUMP',
      favorite: false,
    },
    {
      ticker: 'IQ',
      shtSignal: 'HOLD',
      mdmSignal: 'HOLD',
      lngSignal: 'DUMP',
      favorite: true,
    },
    {
      ticker: 'OPEN',
      shtSignal: 'WAIT',
      mdmSignal: 'WAIT',
      lngSignal: 'HOLD',
      favorite: false,
    },
    {
      ticker: 'SOUN',
      shtSignal: 'WAIT',
      mdmSignal: 'WAIT',
      lngSignal: 'DUMP',
      favorite: false,
    },
    {
      ticker: 'ATCX',
      shtSignal: 'WAIT',
      mdmSignal: 'WAIT',
      lngSignal: 'SELL',
      favorite: false,
    },
    {
      ticker: 'PRDS',
      shtSignal: 'WAIT',
      mdmSignal: 'HOLD',
      lngSignal: 'DUMP',
      favorite: false,
    },
    {
      ticker: 'SFIX',
      shtSignal: 'SELL',
      mdmSignal: 'SELL',
      lngSignal: 'BUY',
      favorite: false,
    },
    {
      ticker: 'SYM',
      shtSignal: 'SELL',
      mdmSignal: 'WAIT',
      lngSignal: 'SELL',
      favorite: false,
    },
    {
      ticker: 'GPRE',
      shtSignal: 'WAIT',
      mdmSignal: 'BUY',
      lngSignal: 'HOLD',
      favorite: false,
    },
    {
      ticker: 'ABOS',
      shtSignal: 'HOLD',
      mdmSignal: 'HOLD',
      lngSignal: 'BUY',
      favorite: false,
    },
    {
      ticker: 'WVE',
      shtSignal: 'SELL',
      mdmSignal: 'DUMP',
      lngSignal: 'BUY',
      favorite: true,
    },
    {
      ticker: 'ALGM',
      shtSignal: 'HOLD',
      mdmSignal: 'SELL',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'CASA',
      shtSignal: 'BUY',
      mdmSignal: 'BUY',
      lngSignal: 'BUY',
      favorite: false,
    },
    {
      ticker: 'EH',
      shtSignal: 'WAIT',
      mdmSignal: 'WAIT',
      lngSignal: 'SELL',
      favorite: false,
    },
    {
      ticker: 'ALPN',
      shtSignal: 'HOLD',
      mdmSignal: 'HOLD',
      lngSignal: 'SELL',
      favorite: false,
    },
    {
      ticker: 'APPH',
      shtSignal: 'HOLD',
      mdmSignal: 'BUY',
      lngSignal: 'HOLD',
      favorite: false,
    },
    {
      ticker: 'INTR',
      shtSignal: 'BUY',
      mdmSignal: 'WAIT',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'GLBE',
      shtSignal: 'DUMP',
      mdmSignal: 'DUMP',
      lngSignal: 'HOLD',
      favorite: false,
    },
    {
      ticker: 'CARA',
      shtSignal: 'HOLD',
      mdmSignal: 'SELL',
      lngSignal: 'SELL',
      favorite: false,
    },
    {
      ticker: 'BMO',
      shtSignal: 'DUMP',
      mdmSignal: 'BUY',
      lngSignal: 'HOLD',
      favorite: true,
    },
    {
      ticker: 'TVE',
      shtSignal: 'BUY',
      mdmSignal: 'BUY',
      lngSignal: 'BUY',
      favorite: false,
    },
    {
      ticker: 'T',
      shtSignal: 'DUMP',
      mdmSignal: 'WAIT',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'BIR',
      shtSignal: ' BUY ',
      mdmSignal: 'BUY',
      lngSignal: ' BUY ',
      favorite: false,
    },
    {
      ticker: 'LUN',
      shtSignal: 'DUMP',
      mdmSignal: 'WAIT',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'WEED',
      shtSignal: 'DUMP',
      mdmSignal: 'WAIT',
      lngSignal: 'SELL',
      favorite: false,
    },
    {
      ticker: 'PEI',
      shtSignal: ' BUY ',
      mdmSignal: ' BUY ',
      lngSignal: 'BUY',
      favorite: false,
    },
    {
      ticker: 'DML',
      shtSignal: 'SELL',
      mdmSignal: 'WAIT',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'AC',
      shtSignal: 'SELL',
      mdmSignal: ' BUY ',
      lngSignal: 'SELL',
      favorite: false,
    },
    {
      ticker: 'BCE',
      shtSignal: 'DUMP',
      mdmSignal: 'WAIT',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'XEG',
      shtSignal: 'DUMP',
      mdmSignal: 'SELL',
      lngSignal: 'WAIT',
      favorite: true,
    },
    {
      ticker: 'XIU',
      shtSignal: 'SELL',
      mdmSignal: 'WAIT',
      lngSignal: 'WAIT',
      favorite: false,
    },
    {
      ticker: 'BITF',
      shtSignal: 'WAIT',
      mdmSignal: 'DUMP',
      lngSignal: 'BUY',
      favorite: false,
    },
    {
      ticker: 'FTS',
      shtSignal: 'BUY',
      mdmSignal: 'WAIT',
      lngSignal: 'WAIT',
      favorite: false,
    },
  ],
};
