export const subscriptions = {
  adFree: {
    cost: '$4.99',
    currency: 'USD',
    frequency: 'One Time',
    details: {
      adFree: 'YES',
      cryptoSignals: '10',
      stockSignals: '10',
      inAppAlerts: 'YES',
      favorites: '0',
      paperTrade: 'NO',
      pushNotifications: 'NO',
      emailAlerts: 'NO',
      smsAlerts: 'NO',
      liveTrade: 'NO',
    },
  },
  novice: {
    cost: '$4.99',
    currency: 'USD',
    frequency: 'Monthly',
    details: {
      adFree: 'YES',
      cryptoSignals: '20',
      stockSignals: '20',
      inAppAlerts: 'YES',
      favorites: '10',
      paperTrade: 'NO',
      pushNotifications: 'NO',
      emailAlerts: 'NO',
      smsAlerts: 'NO',
      liveTrade: 'NO',
    },
  },
  apprentice: {
    cost: '$9.99',
    currency: 'USD',
    frequency: 'Monthly',
    details: {
      adFree: 'YES',
      cryptoSignals: '30',
      stockSignals: '30',
      inAppAlerts: 'YES',
      favorites: '15',
      paperTrade: 'YES',
      pushNotifications: 'YES',
      emailAlerts: 'NO',
      smsAlerts: 'NO',
      liveTrade: 'NO',
    },
  },
  magician: {
    cost: '$14.99',
    currency: 'USD',
    frequency: 'Monthly',
    details: {
      adFree: 'YES',
      cryptoSignals: '40',
      stockSignals: '40',
      inAppAlerts: 'YES',
      favorites: '20',
      paperTrade: 'YES',
      pushNotifications: 'YES',
      emailAlerts: 'YES',
      smsAlerts: 'YES',
      liveTrade: 'NO',
    },
  },
  genie: {
    cost: '$19.99',
    currency: 'USD',
    frequency: 'Monthly',
    details: {
      adFree: 'YES',
      cryptoSignals: '50',
      stockSignals: '50',
      inAppAlerts: 'YES',
      favorites: '25',
      paperTrade: 'YES',
      pushNotifications: 'YES',
      emailAlerts: 'YES',
      smsAlerts: 'YES',
      liveTrade: 'YES',
    },
  },
};

