export const defaultUserData = {
  userID: '',
  subscriptionLevel: 0,
  memberSince: '',
  username: '',
  password: '',
  firstName: '',
  lastName: '',
  email: '',
  mobile: '',
  country: '',
  territory: '',
  address: '',
  city: '',
  zip: '',
  language: '',
  theme: '',
  cryptoExchange: '',
  cryptoKey: '',
  cryptoSecretKey: '',
  stockExchange: '',
  stockKey: '',
  stockSecretKey: '',
};
